CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'manager',
        is_active INTEGER NOT NULL DEFAULT 1,
        created_by INTEGER,
        totp_secret TEXT,
        totp_enabled INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, session_version INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
      );
CREATE TABLE audit_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER,
        action TEXT NOT NULL,
        table_name TEXT NOT NULL,
        record_id INTEGER,
        timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, old_values TEXT, new_values TEXT, reason TEXT,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
      );
CREATE TABLE flocks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch TEXT NOT NULL UNIQUE,
        breed TEXT,
        received INTEGER NOT NULL DEFAULT 0,
        date_received TEXT,
        supplier TEXT,
        cost_per_chick DOUBLE PRECISION NOT NULL DEFAULT 0,
        house TEXT,
        mortality INTEGER NOT NULL DEFAULT 0,
        culls INTEGER NOT NULL DEFAULT 0,
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      , is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, updated_at TEXT, placement_date TEXT, initial_bird_count INTEGER NOT NULL DEFAULT 0, current_bird_count INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Closed')), stage TEXT NOT NULL DEFAULT 'Laying', closed_date TEXT, mortality_baseline_date TEXT, mortality_reconciled INTEGER NOT NULL DEFAULT 0, mortality_reconciled_by INTEGER REFERENCES users(id), mortality_reconciled_at TEXT, mortality_existing_current INTEGER);
CREATE TABLE feed_entries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type TEXT NOT NULL CHECK(type IN ('Chick Mash','Growers','Layers')),
        supplier TEXT,
        received_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
        cost_per_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
        consumed_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
        date TEXT NOT NULL,
        flock_id INTEGER,
        notes TEXT, total_cost DOUBLE PRECISION NOT NULL DEFAULT 0, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, created_at TEXT, updated_at TEXT, supplier_id INTEGER,
        FOREIGN KEY (flock_id) REFERENCES flocks(id) ON DELETE SET NULL
      );
CREATE TABLE purchases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category TEXT NOT NULL,
        item TEXT NOT NULL,
        supplier TEXT,
        reference TEXT,
        date TEXT NOT NULL,
        quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        payment_status TEXT NOT NULL DEFAULT 'Paid',
        amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
        notes TEXT
      , is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, created_at TEXT, updated_at TEXT, supplier_id INTEGER, feed_type TEXT, total DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE TABLE production (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date TEXT NOT NULL,
        flock_id INTEGER,
        trays INTEGER NOT NULL DEFAULT 0,
        loose_eggs INTEGER NOT NULL DEFAULT 0,
        birds_sold INTEGER NOT NULL DEFAULT 0,
        avg_weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
        mortality INTEGER NOT NULL DEFAULT 0,
        notes TEXT, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, created_at TEXT, updated_at TEXT, damaged_eggs INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (flock_id) REFERENCES flocks(id) ON DELETE SET NULL
      );
CREATE TABLE customers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        phone TEXT,
        location TEXT,
        notes TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      , customer_code TEXT, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, updated_at TEXT, email TEXT, status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Inactive')));
CREATE TABLE sales (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date TEXT NOT NULL,
        customer_id INTEGER,
        type TEXT NOT NULL,
        quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        weight_kg DOUBLE PRECISION NOT NULL DEFAULT 0,
        total DOUBLE PRECISION NOT NULL DEFAULT 0,
        payment_status TEXT NOT NULL DEFAULT 'Paid',
        amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
        notes TEXT, price_per_tray DOUBLE PRECISION NOT NULL DEFAULT 0, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, created_at TEXT, updated_at TEXT,
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
      );
CREATE TABLE supplier_debts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier TEXT NOT NULL UNIQUE,
        opening_debt DOUBLE PRECISION NOT NULL DEFAULT 0,
        feed_credit DOUBLE PRECISION NOT NULL DEFAULT 0,
        other_credit DOUBLE PRECISION NOT NULL DEFAULT 0,
        paid DOUBLE PRECISION NOT NULL DEFAULT 0,
        notes TEXT
      , supplier_code TEXT, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, created_by INTEGER, updated_by INTEGER, created_at TEXT, updated_at TEXT, supplier_id INTEGER);
CREATE TABLE expenses (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category TEXT NOT NULL,
        item TEXT NOT NULL,
        date TEXT NOT NULL,
        amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        notes TEXT,
        created_by INTEGER,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, is_voided INTEGER NOT NULL DEFAULT 0, voided_by INTEGER, voided_at TEXT, void_reason TEXT, updated_by INTEGER, updated_at TEXT,
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
      );
CREATE TABLE pricing (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        value DOUBLE PRECISION NOT NULL DEFAULT 0,
        updated_by INTEGER,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
      );
CREATE TABLE suppliers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        phone TEXT,
        location TEXT,
        products TEXT,
        status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Inactive')),
        is_voided INTEGER NOT NULL DEFAULT 0,
        voided_by INTEGER,
        voided_at TEXT,
        void_reason TEXT,
        created_by INTEGER,
        updated_by INTEGER,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (voided_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
      );
CREATE TABLE payments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id INTEGER REFERENCES sales(id), purchase_id INTEGER REFERENCES purchases(id),
        date TEXT NOT NULL, amount DOUBLE PRECISION NOT NULL CHECK(amount>0), reference TEXT NOT NULL DEFAULT '',
        is_voided INTEGER NOT NULL DEFAULT 0, void_reason TEXT, voided_by INTEGER, voided_at TEXT,
        created_by INTEGER, updated_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK ((sale_id IS NULL) <> (purchase_id IS NULL))
      );
CREATE TABLE feed_usage (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date TEXT NOT NULL, flock_id INTEGER REFERENCES flocks(id),
        type TEXT NOT NULL CHECK(type IN ('Chick Mash','Growers','Layers')),
        consumed_kg DOUBLE PRECISION NOT NULL CHECK(consumed_kg>0), notes TEXT,
        is_voided INTEGER NOT NULL DEFAULT 0, void_reason TEXT, voided_by INTEGER, voided_at TEXT,
        created_by INTEGER, updated_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
CREATE TABLE migration_notes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message TEXT NOT NULL);
INSERT INTO pricing(name,value) VALUES('egg_tray',0);
CREATE TABLE sessions(sid TEXT PRIMARY KEY,data TEXT NOT NULL,expires BIGINT NOT NULL);
CREATE INDEX session_expiry ON sessions(expires);
CREATE INDEX idx_audit_user ON audit_log(user_id);
CREATE INDEX idx_audit_table_record ON audit_log(table_name, record_id);
CREATE INDEX idx_feed_date ON feed_entries(date);
CREATE INDEX idx_feed_flock ON feed_entries(flock_id);
CREATE INDEX idx_purchase_date ON purchases(date);
CREATE INDEX idx_production_date ON production(date);
CREATE INDEX idx_production_flock ON production(flock_id);
CREATE INDEX idx_sales_date ON sales(date);
CREATE INDEX idx_sales_customer ON sales(customer_id);
CREATE UNIQUE INDEX idx_customers_code ON customers(customer_code);
CREATE UNIQUE INDEX idx_supplier_debts_code ON supplier_debts(supplier_code);
CREATE INDEX idx_expenses_date ON expenses(date);
CREATE INDEX idx_expenses_created_by ON expenses(created_by);
CREATE INDEX idx_flocks_voided ON flocks(is_voided);
CREATE INDEX idx_feed_entries_voided ON feed_entries(is_voided);
CREATE INDEX idx_purchases_voided ON purchases(is_voided);
CREATE INDEX idx_production_voided ON production(is_voided);
CREATE INDEX idx_customers_voided ON customers(is_voided);
CREATE INDEX idx_sales_voided ON sales(is_voided);
CREATE INDEX idx_supplier_debts_voided ON supplier_debts(is_voided);
CREATE INDEX idx_expenses_voided ON expenses(is_voided);
CREATE INDEX idx_audit_timestamp ON audit_log(timestamp);
CREATE INDEX idx_flocks_status ON flocks(status);
CREATE INDEX idx_customers_status ON customers(status);
CREATE INDEX idx_suppliers_status ON suppliers(status);
CREATE INDEX idx_suppliers_name ON suppliers(name);
CREATE INDEX idx_feed_supplier ON feed_entries(supplier_id);
CREATE INDEX idx_purchase_supplier ON purchases(supplier_id);
CREATE INDEX idx_debt_supplier ON supplier_debts(supplier_id);
CREATE INDEX idx_payments_sale ON payments(sale_id,is_voided);
CREATE INDEX idx_payments_purchase ON payments(purchase_id,is_voided);
CREATE INDEX idx_usage_type_date ON feed_usage(type,date);
