'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:2}).format(n||0);
let fieldSequence=0;
let me=null,permissions=[],page='dashboard',generation=0,showVoided=false,rows=[],farmToday='',currentPrice=0;
const can=p=>permissions.includes('*')||permissions.includes(p);
const nav=[['dashboard','Dashboard','dashboard:read'],['flocks','Flocks','flocks:read'],['production','Production','production:read'],['feed','Feed Usage & Stock','feed:read'],['purchases','Purchases & Payments','purchases:read'],['customers','Customers','customers:read'],['suppliers','Suppliers','suppliers:read'],['sales','Sales & Receipts','sales:read'],['expenses','Expenses','expenses:read'],['reports','Reports','reports:read'],['audit','Audit Log','audit:read'],['legacy','Legacy Records','audit:read'],['settings','Settings & Security','settings:read']];
const schemas={
 flocks:[['batch','Batch number','text'],['breed','Breed','text'],['placement_date','Placement date','date'],['initial_bird_count','Initial birds','integer'],['stage','Stage','select','Laying|Growing'],['status','Status','select','Active|Closed'],['closed_date','Closure date (closed flocks)','optional-date'],['house','House / pen','optional'],['mortality','Opening mortality (not daily deaths)','integer'],['mortality_baseline_date','Opening mortality includes deaths through','optional-date'],['culls','Culls (cumulative adjustment)','integer']],
 customers:[['name','Customer name','text'],['phone','Phone','optional'],['email','Email','email'],['location','Location','optional'],['status','Status','select','Active|Inactive']],
 suppliers:[['name','Supplier name','text'],['phone','Phone','optional'],['location','Location','optional'],['products','Products','optional'],['status','Status','select','Active|Inactive']],
 production:[['date','Date','date'],['flock_id','Flock batch','lookup','flocks'],['trays','Collected full trays (30 eggs)','integer'],['loose_eggs','Collected loose eggs (0–29)','integer'],['damaged_eggs','Damaged eggs included in collection','integer'],['mortality','Bird deaths today','integer']],
 feed:[['date','Usage date','date'],['flock_id','Flock batch','lookup','flocks'],['type','Feed type','select','Chick Mash|Growers|Layers'],['consumed_kg','Feed consumed (kg)','number']],
 purchases:[['date','Purchase date','date'],['supplier_id','Supplier','lookup','suppliers'],['category','Category','select','Feed|Chicks|Animal Health|Equipment|Labour / Services|Other'],['item','Item / description','text'],['feed_type','Feed type (feed purchases only)','select','Chick Mash|Growers|Layers'],['quantity','Quantity (kg for feed)','number'],['total','Total purchase cost (KES)','number'],['amount_paid','Initial amount paid (KES)','number'],['reference','Invoice reference','optional']],
 sales:[['date','Sale date','date'],['customer_id','Customer','lookup','customers'],['quantity','Trays sold','integer'],['amount_paid','Initial amount received (KES)','number']],
 expenses:[['date','Date','date'],['category','Category','select','Labour|Veterinary / Medication|Transport|Electricity|Water|Repairs|Other'],['item','Description','text'],['amount','Expense amount (KES)','number']]
};
const columns={flocks:['batch','breed','stage','status','initial_bird_count','current_bird_count'],customers:['customer_code','name','phone','status','outstanding_balance'],suppliers:['supplier_code','name','phone','status','outstanding_balance'],production:['date','flock_batch','trays','loose_eggs','damaged_eggs','mortality'],feed:['date','flock_batch','type','consumed_kg'],purchases:['date','supplier','item','feed_type','quantity','unit_cost','total','amount_paid','outstanding','payment_status'],sales:['date','customer','quantity','price_per_tray','total','amount_paid','outstanding','payment_status'],expenses:['date','category','item','amount']};
async function api(path,method='GET',body){
 const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const result=await response.json().catch(()=>({error:'Unexpected server response'}));
 if(response.status===401&&path!=='/auth/login'){me=null;$('#app').hidden=true;$('#login').hidden=false;$('#dialog').close()}
 if(!response.ok)throw new Error(result.error||'Request failed');return result;
}
function toast(message){$('#toast').textContent=message;setTimeout(()=>{$('#toast').textContent=''},5000)}
async function submit(form,fn){const button=form.querySelector('button[type=submit],button.primary');if(button?.disabled)return;const error=form.querySelector('.error');if(error)error.textContent='';if(button)button.disabled=true;try{await fn(Object.fromEntries(new FormData(form)))}catch(e){if(error)error.textContent=e.message;else toast(e.message)}finally{if(button)button.disabled=false}}
function navigation(){const term=$('#search').value.toLowerCase();$('#nav').innerHTML=nav.filter(n=>can(n[2])&&n[1].toLowerCase().includes(term)).map(n=>`<button data-page="${n[0]}" ${page===n[0]?'aria-current="page"':''}>${n[1]}</button>`).join('')||'<p>No matching section</p>'}
function table(kind,data,actions=true){const cols=columns[kind];if(!data.length)return '<p class="muted">No records yet.</p>';return `<div class="tablewrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${data.map(r=>`<tr class="${r.is_voided?'voided':''}">${cols.map(c=>`<td>${esc(typeof r[c]==='number'&&!Number.isInteger(r[c])?Number(r[c].toFixed(2)):r[c])}</td>`).join('')}${actions?`<td>${r.can_correct?`<button data-action="edit" data-id="${r.id}">Edit</button><button data-action="void" data-id="${r.id}">Void</button>`:''}${['sales','purchases'].includes(kind)?`<button data-action="payments" data-id="${r.id}">Payments</button>`:''}${['customers','suppliers'].includes(kind)?`<button data-action="history" data-id="${r.id}">History</button>`:''}${r.is_voided?'Voided':''}</td>`:''}</tr>`).join('')}</tbody></table></div>`}
function field([name,label,type,options],value,lookups={}){
 const id='f-'+name+'-'+(++fieldSequence),attrs=`id="${id}" name="${name}"`,optional=['optional','optional-date','email'].includes(type);
 if(type==='select')return `<div><label for="${id}">${label}</label><select ${attrs}>${options.split('|').map(v=>`<option ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select></div>`;
 if(type==='lookup')return `<div><label for="${id}">${label}</label><select ${attrs} required><option value="">Select ${options}</option>${(lookups[options]||[]).map(r=>`<option value="${r.id}" ${Number(value)===r.id?'selected':''}>${esc(r.batch||r.name)}${r.status!=='Active'?' (historical)':''}</option>`).join('')}</select></div>`;
 const actual=['integer','number'].includes(type)?'number':type==='optional'?'text':type==='optional-date'?'date':type;
 return `<div><label for="${id}">${label}</label><input ${attrs} type="${actual}" ${optional?'':'required'} ${actual==='number'?`min="0" step="${type==='integer'?'1':'0.001'}"`:''} ${actual==='date'?`max="${farmToday}"`:''} value="${esc(value??(type==='date'?farmToday:['integer','number'].includes(type)?0:''))}"></div>`;
}
async function formHTML(kind,row){
 const lookups={};for(const f of schemas[kind].filter(f=>f[2]==='lookup')){let data=await api('/'+f[3]);lookups[f[3]]=data.filter(r=>r.status==='Active'||r.id===row?.[f[0]])}
 const fields=schemas[kind].filter(f=>!row||f[0]!=='amount_paid');
 return `<form id="${row?'editRecordForm':'recordForm'}" class="formgrid">${fields.map(f=>field(f,row?.[f[0]],lookups)).join('')}${kind==='suppliers'?'':field(['notes','Notes','optional'],row?.notes)}${row?field(['reason','Reason for correction','text'],''):''}<p data-calculation class="notice form-actions"></p><div class="form-actions"><button type="submit" class="primary">${row?'Save correction':'Save record'}</button><span class="error" role="alert"></span></div></form>`;
}
function bindRecord(kind,row){
 const form=$(row?'#editRecordForm':'#recordForm');if(!form)return;
 const calculate=()=>{
   const v=Object.fromEntries(new FormData(form)),out=form.querySelector('[data-calculation]');out.hidden=false;
   if(kind==='sales')out.textContent=`Price per tray: ${money(row?.price_per_tray??currentPrice)} · Total sale: ${money(Number(v.quantity||0)*(row?.price_per_tray??currentPrice))}. Payment status is calculated automatically.`;
   else if(kind==='purchases'){out.textContent=`Cost per unit / kg: ${money(Number(v.quantity)>0?Number(v.total)/Number(v.quantity):0)}. Outstanding: ${money(Number(v.total)-(row?.amount_paid??Number(v.amount_paid||0)))}`;form.elements.feed_type.disabled=v.category!=='Feed'}
   else if(kind==='production')out.textContent=`Collected: ${Number(v.trays||0)*30+Number(v.loose_eggs||0)} eggs · Usable: ${Number(v.trays||0)*30+Number(v.loose_eggs||0)-Number(v.damaged_eggs||0)} eggs`;
   else if(kind==='flocks')out.textContent='Record daily deaths in Production. Opening mortality is a separate baseline and must not duplicate daily records. Stage changes apply to current performance reporting.';
   else out.hidden=true;
 };
 form.addEventListener('input',calculate);form.addEventListener('change',calculate);calculate();
 form.onsubmit=e=>{e.preventDefault();submit(form,async body=>{await api('/'+kind+(row?'/'+row.id:''),row?'PUT':'POST',body);$('#dialog').close();toast('Record saved');await go(kind)})};
}
async function go(next){
 page=next;const token=++generation;navigation();document.body.classList.remove('menu-open');$('#menuToggle').setAttribute('aria-expanded','false');
 const title=nav.find(n=>n[0]===page)?.[1]||page;$('#main').innerHTML=`<h1>${title}</h1><p>Loading…</p>`;
 try{
  if(page==='dashboard'){const d=await api('/dashboard');if(token!==generation)return;farmToday=d.today;renderDashboard(d);return}
  if(schemas[page]){
   const kind=page;const data=await api('/'+kind+(showVoided?'?include_voided=1':''));
   if(kind==='sales')currentPrice=(await api('/pricing')).find(r=>r.name==='egg_tray').value;
   const form=can(kind+':write')?await formHTML(kind):'';
   const stock=kind==='feed'?await api('/feed-stock'):null;if(token!==generation)return;rows=data;
   $('#main').innerHTML=`<h1>${title}</h1>${kind==='feed'?`<p>Record feed use against a flock. ${can('purchases:write')?'<button data-page="purchases">Record a feed purchase</button>':''}</p><div class="cards">${stock.map(s=>`<div class="card">${esc(s.type)}<strong>${s.available_kg} kg</strong></div>`).join('')}</div>`:''}${form?`<section class="panel"><h2>New ${kind==='feed'?'feed usage':kind==='sales'?'sale':kind==='purchases'?'purchase':'record'}</h2>${form}</section>`:''}<section class="panel"><div class="sectionhead"><h2>Records</h2><label><input type="checkbox" id="showVoided" ${showVoided?'checked':''}> Show voided</label></div>${table(kind,data)}</section>`;
   bindRecord(kind);$('#showVoided').onchange=e=>{showVoided=e.target.checked;go(kind)};return;
  }
  if(page==='reports'){$('#main').innerHTML='<h1>Reports</h1><section class="panel"><p>Reports use the same calculations as the dashboard and exclude voided transactions.</p><button data-download="report">Download Farm PDF</button> <button data-download="production-report">Download Production PDF</button></section>';return}
  if(page==='audit'){const data=await api('/audit-log');if(token!==generation)return;$('#main').innerHTML=`<h1>Audit Log</h1><p>Latest 500 events. Edits and voids retain their reasons and snapshots.</p><section class="panel tablewrap"><table><thead><tr><th>When / Who</th><th>Action / Record</th><th>Reason</th><th>Before</th><th>After</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.timestamp)}<br>${esc(r.username)}</td><td>${esc(r.action)} · ${esc(r.table_name)} #${r.record_id??''}</td><td>${esc(r.reason)}</td><td><pre>${esc(r.old_values)}</pre></td><td><pre>${esc(r.new_values)}</pre></td></tr>`).join('')}</tbody></table></section>`;return}
  if(page==='legacy'){const data=await api('/legacy');if(token!==generation)return;$('#main').innerHTML=`<h1>Legacy Records</h1><p class="notice">Read-only historical feed and debt records. Feed quantities contribute to stock; legacy debt is shown separately and excluded from purchase-linked balances until reconciled. Avoid entering the same purchase twice.</p>${data.notes.map(n=>`<p>${esc(n.message)}</p>`).join('')}<section class="panel"><h2>Legacy feed entries</h2>${plainTable(data.feed,['date','type','supplier','received_kg','consumed_kg','total_cost','is_voided'])}<h2>Legacy supplier debts</h2>${plainTable(data.debts,['supplier','opening_debt','feed_credit','other_credit','paid','remaining','is_voided'])}</section>`;return}
  if(page==='settings')await settings(token);
 }catch(e){if(token===generation)$('#main').innerHTML=`<h1>${title}</h1><p class="error" role="alert">${esc(e.message)}</p><button data-page="${page}">Retry</button>`}
}
function plainTable(data,cols){return data.length?`<div class="tablewrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p>No records.</p>'}
function renderDashboard(d){
 const m=d.metrics,items=[['Eggs today',m.eggsToday],['Production rate',m.productionRate===null?'N/A':m.productionRate+'%'],['Active birds',m.activeBirds],['Mortality',m.mortality],['Eggs collected (all time)',m.eggs],['Damaged eggs (all time)',m.damagedEggs],['Feed consumed (all time)',Number(m.feedConsumed.toFixed(3))+' kg']];
 if(can('sales:read'))items.push(['Sales',money(m.sales)],['Purchases',money(m.purchases)],['Operating expenses',money(m.expenses)],['Net profit (simplified)',money(m.netProfit)],['Customer outstanding',money(m.customerOutstanding)],['Supplier outstanding',money(m.supplierOutstanding)]);
 const max=Math.max(1,...d.trend.map(r=>r.eggs));const points=d.trend.map((r,i)=>`${20+i*760/Math.max(1,d.trend.length-1)},${190-r.eggs/max*165}`).join(' ');
 $('#main').innerHTML=`<h1>Farm Dashboard</h1><p>${esc(d.today)} · Farm time · Production rate uses today's collected eggs from laying flocks divided by their opening live birds.</p><div class="cards">${items.map(([label,value])=>`<div class="card">${label}<strong>${value}</strong></div>`).join('')}</div>${d.profitBasis?`<p class="notice">${esc(d.profitBasis)}</p>`:''}<section class="panel"><h2>Feed stock</h2><div class="cards">${d.stock.map(s=>`<div class="card">${esc(s.type)}<strong>${s.available_kg} kg</strong>${s.available_kg<=0?'No available stock':''}</div>`).join('')}</div></section><section class="panel"><h2>Daily production trend</h2>${d.trend.length?`<svg class="trend" viewBox="0 0 800 220" role="img" aria-label="Daily collected eggs; exact values in the table below"><polyline points="${points}"/></svg>${plainTable(d.trend,['date','eggs','damaged'])}`:'<p>Record production to see the trend.</p>'}</section><section class="panel"><h2>Recent production</h2>${table('production',d.production,false)}</section>${d.notes.length?`<section class="panel"><h2>Data reconciliation</h2>${d.notes.map(n=>`<p class="notice">${esc(n)}</p>`).join('')}</section>`:''}`;
}
function modal(html){$('#dialogContent').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal()}
async function edit(id){const kind=page,row=rows.find(r=>r.id===id);modal(`<h2>Edit ${kind} #${id}</h2>${await formHTML(kind,row)}`);bindRecord(kind,row)}
function voidEntry(id){const kind=page;modal(`<h2>Void ${kind} #${id}</h2><p>The record remains in history and is excluded from totals.</p><form id="voidForm">${field(['reason','Reason','text'],'')}<p class="error" role="alert"></p><button type="submit" class="primary">Confirm void</button></form>`);$('#voidForm').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api(`/${kind}/${id}/void`,'POST',body);$('#dialog').close();toast('Record voided');await go(kind)})}}
async function payments(id){
 const kind=page,row=rows.find(r=>r.id===id),data=await api(`/${kind}/${id}/payments`);
 modal(`<h2>${kind==='sales'?'Customer receipts':'Supplier payments'} · #${id}</h2><p>Total ${money(row.total)} · Outstanding ${money(row.outstanding)}</p>${plainTable(data,['id','date','amount','reference','is_voided','void_reason'])}${can(kind+':write')?data.filter(r=>!r.is_voided).map(r=>`<button data-payment-void="${r.id}" data-parent="${id}">Void payment #${r.id}</button>`).join(''):''}${!row.is_voided&&row.outstanding>0&&can(kind+':write')?`<h3>Add payment</h3><form id="paymentForm">${field(['date','Payment date','date'],farmToday)}${field(['amount','Amount (KES)','number'],row.outstanding)}${field(['reference','Reference','optional'],'')}<p class="error" role="alert"></p><button type="submit" class="primary">Record payment</button></form>`:''}`);
 const form=$('#paymentForm');if(form)form.onsubmit=e=>{e.preventDefault();submit(form,async body=>{await api(`/${kind}/${id}/payments`,'POST',body);$('#dialog').close();toast('Payment recorded');await go(kind)})};
}
async function history(id){const kind=page,d=await api(`/${kind}/${id}/history`),resource=kind==='customers'?'sales':'purchases';modal(`<h2>Transaction and payment history</h2>${table(resource,d.records,false)}<h3>Payments</h3>${plainTable(d.payments,['date','amount','reference','is_voided','void_reason'])}`)}
async function settings(token){
 const auth=await api('/auth/me');me=auth.user;let users=[],prices=[];if(can('users:manage')){users=await api('/users');prices=await api('/pricing')}if(token!==generation)return;
 $('#main').innerHTML=`<h1>Settings & Security</h1><section class="panel"><h2>Change your password</h2><form id="passwordForm"><label for="currentPassword">Current password</label><input id="currentPassword" name="current_password" type="password" autocomplete="current-password" required><label for="newPassword">New password (12+ characters)</label><input id="newPassword" name="new_password" type="password" autocomplete="new-password" minlength="12" required><p class="error" role="alert"></p><button type="submit" class="primary">Change password</button></form><h2>Two-factor authentication</h2><p>${me.totp_enabled?'Enabled':'Not enabled'}</p><button id="twoFactor">${me.totp_enabled?'Disable 2FA':'Set up 2FA'}</button></section>${can('users:manage')?`<section class="panel"><h2>Egg selling price</h2><form id="priceForm">${field(['value','Current price per tray (KES)','number'],prices[0].value)}${field(['reason','Reason for price change','text'],'')}<p>Previous sales retain their original price.</p><p class="error" role="alert"></p><button type="submit" class="primary">Save price</button></form></section><section class="panel"><h2>Users</h2>${plainTable(users,['username','role','is_active','totp_enabled'])}${users.map(u=>`<button data-user="${u.id}">Manage ${esc(u.username)}</button>`).join('')}<h3>Add user</h3><form id="userForm">${field(['username','Username','text'],'')}<label for="userPassword">Initial password</label><input id="userPassword" name="password" type="password" minlength="12" required autocomplete="new-password">${field(['role','Role','select','manager|production_staff|admin'],'manager')}<p class="error" role="alert"></p><button type="submit" class="primary">Create user</button></form></section>`:''}`;
 $('#passwordForm').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api('/auth/password','POST',body);e.target.reset();toast('Password changed; other sessions were invalidated')})};
 $('#twoFactor').onclick=()=>twoFactor().catch(e=>toast(e.message));
 if(can('users:manage')){
  $('#priceForm').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api('/pricing/egg_tray','PUT',body);toast('Price updated')})};
  $('#userForm').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api('/users','POST',body);toast('User created');await go('settings')})};
  document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>manageUser(users.find(u=>u.id===Number(b.dataset.user))));
 }
}
function manageUser(u){modal(`<h2>Manage ${esc(u.username)}</h2><form id="manageUser">${field(['role','Role','select','admin|manager|production_staff'],u.role)}${field(['active','Account status','select','Active|Inactive'],u.is_active?'Active':'Inactive')}<label for="resetPassword">Optional replacement password (12+ characters)</label><input id="resetPassword" name="password" type="password" autocomplete="new-password"><label><input name="reset_2fa" type="checkbox"> Reset lost authenticator access</label>${field(['reason','Reason for change','text'],'')}<p class="error" role="alert"></p><button type="submit" class="primary">Save user</button></form>`);$('#manageUser').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{body.is_active=body.active==='Active';body.reset_2fa=body.reset_2fa==='on';await api('/users/'+u.id,'PUT',body);$('#dialog').close();toast('User updated; their sessions were invalidated');await go('settings')})}}
async function twoFactor(){
 if(me.totp_enabled){modal('<h2>Disable two-factor authentication</h2><form id="twoForm"><label for="disablePassword">Password</label><input id="disablePassword" type="password" name="password" required autocomplete="current-password"><label for="disableToken">Current authenticator code</label><input id="disableToken" name="token" inputmode="numeric" required><p class="error" role="alert"></p><button type="submit" class="primary">Disable 2FA</button></form>')}
 else{const d=await api('/auth/2fa/setup','POST',{});modal(`<h2>Set up two-factor authentication</h2><p>Scan this code. Setup expires in 10 minutes.</p><img src="${d.qr}" alt="Authenticator setup QR code"><p>Manual secret: ${esc(d.secret)}</p><form id="twoForm"><label for="twoToken">Authenticator code</label><input id="twoToken" name="token" inputmode="numeric" required><p class="error" role="alert"></p><button type="submit" class="primary">Enable 2FA</button></form>`)}
 $('#twoForm').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api('/auth/2fa/'+(me.totp_enabled?'disable':'confirm'),'POST',body);$('#dialog').close();toast('Security settings updated');await go('settings')})};
}
async function download(name){const r=await fetch(`/api/${name}.pdf`);if(!r.ok)throw new Error((await r.json()).error||'Download failed');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`sonia-${name}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.page){await go(b.dataset.page);return}
 if(b.dataset.action){const id=Number(b.dataset.id);await ({edit,void:voidEntry,payments,history}[b.dataset.action])(id)}
 if(b.dataset.download){b.disabled=true;try{await download(b.dataset.download)}finally{b.disabled=false}}
 if(b.dataset.paymentVoid){const id=Number(b.dataset.paymentVoid),kind=page;modal(`<h2>Void payment #${id}</h2><p>Use this for an erroneous receipt/payment. Actual refunds need separate cash accounting.</p><form id="voidPayment">${field(['reason','Reason','text'],'')}<p class="error" role="alert"></p><button type="submit" class="primary">Void payment</button></form>`);$('#voidPayment').onsubmit=e=>{e.preventDefault();submit(e.target,async body=>{await api(`/payments/${id}/void`,'POST',body);$('#dialog').close();toast('Payment voided');await go(kind)})}}
 }catch(error){toast(error.message)}});
$('#loginForm').onsubmit=e=>{e.preventDefault();const form=e.target;$('#loginError').className='error';submit(form,async body=>{const d=await api('/auth/login','POST',body);if(d.requires2fa){$('#loginError').textContent='Enter your current authenticator code.';$('#otp').focus();return}me=d.user;permissions=d.permissions;form.reset();await showApp()})};
async function showApp(){$('#login').hidden=true;$('#app').hidden=false;$('#who').textContent=`${me.username} · ${me.role.replaceAll('_',' ')}`;$('#search').value='';await go('dashboard')}
$('#signout').onclick=async()=>{try{await api('/auth/logout','POST',{});me=null;permissions=[];generation++;$('#dialog').close();$('#app').hidden=true;$('#login').hidden=false;$('#password').value=''}catch(e){toast(e.message)}};
$('#search').oninput=navigation;$('#search').onkeydown=e=>{if(e.key==='Enter')$('#nav button')?.click()};$('#closeDialog').onclick=()=>$('#dialog').close();
$('#menuToggle').onclick=()=>{const open=document.body.classList.toggle('menu-open');$('#menuToggle').setAttribute('aria-expanded',String(open))};
api('/auth/me').then(async d=>{if(d.user&&!me&&generation===0){me=d.user;permissions=d.permissions;await showApp()}}).catch(e=>{$('#loginError').textContent=e.message});
