
const navItems=[['dashboard','⌂','Dashboard'],['flocks','♧','Flocks'],['production','▥','Production'],['feed','♨','Feed Management'],['purchases','🛒','Purchases'],['suppliers','▣','Suppliers'],['customers','♙','Customers'],['sales','◈','Sales'],['expenses','▤','Expenses'],['reports','▥','Reports'],['settings','⚙','Settings']];let me=null,cache={};
async function api(url,opt={}){let r=await fetch('/api'+url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let j=await r.json().catch(()=>({}));if(r.status===401){if(url!=='/auth/login')logout(false);throw new Error(j.error||'Authentication required')}if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function login(){let msg=document.getElementById('loginMsg');msg.classList.add('hidden');try{let j=await api('/auth/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value,otp:otp.value})});if(j.requires2fa){msg.textContent='Enter the current 2FA code from your authenticator app.';msg.className='notice';return}me=j.user;showApp()}catch(e){msg.textContent=e.message;msg.className='notice danger'}}
async function logout(call=true){if(call)try{await api('/auth/logout',{method:'POST'})}catch{}me=null;document.getElementById('app').classList.add('hidden');document.getElementById('login').classList.remove('hidden')}
async function boot(){try{let j=await fetch('/api/auth/me').then(r=>r.json());if(j.user){me=j.user;showApp()}}catch{}}
function showApp(){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('who').textContent=me.username;document.getElementById('avatar').textContent=me.username.slice(0,2).toUpperCase();renderNav();setupSearch();go('dashboard')}
function renderNav(){nav.innerHTML=navItems.map(x=>`<button data-page="${x[0]}" onclick="go('${x[0]}')"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('')}
function setupSearch(){let input=document.getElementById('globalSearch'),results=document.getElementById('searchResults');if(!input||input.dataset.ready)return;input.dataset.ready='true';let search=()=>{let term=input.value.trim().toLowerCase();if(!term){results.innerHTML='';results.classList.remove('visible');return}let matches=navItems.filter(x=>x[2].toLowerCase().includes(term)||x[0].includes(term));results.innerHTML=matches.length?matches.map(x=>`<button type="button" role="option" data-page="${x[0]}">${x[1]} ${x[2]}</button>`).join(''):'<div class="search-empty">No matching section</div>';results.classList.add('visible');results.querySelectorAll('button').forEach(button=>button.onclick=()=>{go(button.dataset.page);input.value='';results.innerHTML='';results.classList.remove('visible');input.blur()})};input.addEventListener('input',search);input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';search();input.blur()}if(e.key==='Enter'){let first=results.querySelector('button');if(first)first.click()}});document.addEventListener('click',e=>{if(!e.target.closest('.search'))results.classList.remove('visible')})}
function go(page){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));main.innerHTML=pages[page]();renderPage(page)}
const pages={dashboard:()=>`<section><div class="dashboard-title"><div><h2>Welcome to Sonia 4.0 Farm</h2><p class="muted">Manage your poultry farm efficiently for better productivity and profit.</p></div><div class="quote">“Healthy hens today, more possibilities tomorrow.”</div></div><div id="metrics" class="cards"></div><div class="grid2"><div class="panel prod-panel"><div class="sectionhead"><div><h3>🥚 Egg Production Trend</h3><span class="muted">Recent recorded egg production</span></div><span class="secondary">Production graph</span></div><div class="canvas"><canvas id="prodChart"></canvas></div></div><div><div class="panel quick"><h3>⚡ Quick Actions</h3><button onclick="go('production')"><i>🥚</i>Record Production</button><button onclick="go('feed')"><i>🌾</i>Add Feed Purchase</button><button onclick="go('sales')"><i>🛒</i>Make a Sale</button><button onclick="go('customers')"><i>👥</i>Add Customer</button><button onclick="go('suppliers')"><i>🚚</i>Add Supplier</button><button onclick="downloadReport()"><i>▤</i>View Reports</button></div><div class="panel" style="margin-top:14px"><h3>📦 Farm Alerts</h3><div id="alerts"></div></div></div></div><div class="fresh-lower"><div class="panel"><h3>🥚 Recent Production Records</h3><div id="flockSummary"></div></div><div class="panel"><h3>🛒 Recent Sales</h3><div id="salesSummary"></div></div><div class="panel"><h3>🌾 Recent Feed Purchases</h3><div id="feedDaily"></div></div></div><div class="fresh-lower"><div class="panel"><h3>Customers</h3><div id="customerSummary"></div></div><div class="panel"><h3>Recent Purchases</h3><div id="recentPurchases"></div></div><div class="panel"><h3>Production Summary</h3><div id="eggSummary"></div></div></div><footer><span><b>Sonia 4.0 Farm</b> &nbsp;|&nbsp; Version 5.0 &nbsp;|&nbsp; Healthy Chicks | Better Yields | A Brighter Future</span><span>Powered by <b>Onlynx Solutions</b></span></footer></section>`,
flocks:()=>crudPage('Flocks','flocks',[['batch','Batch / flock no.','text'],['breed','Breed','text'],['received','Chicks received','number'],['date_received','Date received','date'],['supplier','Supplier','text'],['cost_per_chick','Cost per chick (KES)','number'],['house','House / pen','text'],['mortality','Mortality','number'],['culls','Culls','number']],['batch','breed','received','date_received','supplier','cost_per_chick','house','mortality','culls']),
production:()=>crudPage('Production','production',[['date','Date','date'],['flock_id','Flock Batch No.','lookup','flock'],['trays','Trays','number'],['loose_eggs','Loose eggs','number'],['mortality','Mortality','number']],['date','flock_id','trays','loose_eggs','mortality']),
feed:()=>crudPage('Feed Management','feed',[['type','Feed type','select','Chick Mash|Growers|Layers'],['supplier','Supplier','text'],['received_kg','Feed quantity (kg)','number'],['total_cost','Total feed cost (KES)','number'],['cost_per_kg','Cost per kg (KES)','readonly'],['consumed_kg','Feed intake today (kg)','number'],['date','Date','date'],['flock_id','Flock Batch No.','lookup','flock']],['type','supplier','received_kg','total_cost','cost_per_kg','consumed_kg','date','flock_id']),
purchases:()=>crudPage('Purchases','purchases',[['category','Category','select','Feed|Chicks|Animal Health|Equipment|Labour / Services|Other'],['item','Item','text'],['supplier','Supplier','text'],['reference','Invoice / reference','text'],['date','Date','date'],['quantity','Quantity','number'],['unit_cost','Unit cost (KES)','number'],['payment_status','Payment','select','Paid|Credit / Debt|Part Paid'],['amount_paid','Amount paid (KES)','number']],['category','item','supplier','reference','date','quantity','unit_cost','payment_status','amount_paid']),
suppliers:()=>`<h2>Suppliers & Debt</h2><p class="muted">Capture a supplier debt once, then add feed credit and payments as they happen.</p><div class="panel"><form id="debtForm" class="formgrid">${field('supplier','Supplier','text')} ${field('opening_debt','Opening debt (KES)','number')} ${field('feed_credit','New feed on credit (KES)','number')} ${field('other_credit','Other credit (KES)','number')} ${field('paid','Payment made (KES)','number')}<div><button class="primary">Save debt</button></div></form></div><div class="panel" style="margin-top:14px"><div id="table"></div></div>`,
customers:()=>crudPage('Customers','customers',[['name','Customer name','text'],['phone','Phone','text'],['location','Location','text'],['notes','Notes','text']],['customer_code','name','phone','location']),
sales:()=>crudPage('Sales','sales',[['date','Date','date'],['customer_id','Customer Name','lookup','customer'],['quantity','Quantity (Trays)','number'],['price_per_tray','Price per tray (KES)','number'],['total','Total sale (KES)','readonly'],['payment_status','Payment status','select','Paid|Pending|Part Paid'],['amount_paid','Amount paid (KES)','number']],['date','customer_id','quantity','price_per_tray','total','payment_status','amount_paid']),
expenses:()=>`<h2>Expenses & Finance</h2><p class="muted">Purchases are included in the expense base. Animal Health covers drugs, vaccines and vitamins.</p><div class="cards" id="financeCards"></div>`,
reports:()=>`<h2>Reports</h2><div class="panel"><h3>Farm Management Report</h3><p class="muted">Generate the current database report directly as a PDF.</p><button class="primary" onclick="downloadReport()">Download PDF Report</button></div>`,
settings:()=>`<h2>Settings & Security</h2><div class="panel"><h3>Two-factor authentication</h3><p class="muted">Use an authenticator app such as Google Authenticator, Microsoft Authenticator or Authy.</p><button class="primary" onclick="setup2fa()">${me&&me.role==='admin'?'Set up / manage 2FA':'Set up 2FA'}</button><div id="securityResult" style="margin-top:12px"></div><hr><h3>User management</h3><div id="users"></div></div>`};
function field(n,l,t,opt){return `<div class="field"><label>${l}</label>${t==='select'?`<select name="${n}">${opt.split('|').map(x=>`<option>${x}</option>`).join('')}</select>`:t==='lookup'?`<select name="${n}" data-lookup="${opt}"><option value="">-- Select ${opt} --</option></select>`:t==='readonly'?`<input name="${n}" type="number" step="any" readonly style="background:#f3f6f4">`:`<input name="${n}" type="${t}" step="any">`}</div>`}
function crudPage(title,res,fields,cols){return `<div class="sectionhead"><div><h2>${title}</h2><p class="muted">Record and manage ${title.toLowerCase()}.</p></div></div><div class="panel"><form id="form" class="formgrid">${fields.map(x=>field(...x)).join('')}<div><button class="primary">Save</button></div></form></div><div class="panel" style="margin-top:14px"><div id="table"></div></div>`}
async function renderPage(p){
 if(p==='dashboard')return dashboard();if(p==='suppliers')return suppliersPage();if(p==='expenses')return financePage();if(p==='settings')return settingsPage();
 let res=p==='flocks'?'flocks':p==='production'?'production':p==='feed'?'feed':p==='purchases'?'purchases':p==='customers'?'customers':'sales';
 // Populate relational dropdowns from records already entered in Sonia 4.0.
 for(const sel of document.querySelectorAll('select[data-lookup]')){
   if(sel.dataset.lookup==='customer'){let a=await api('/customers');sel.innerHTML='<option value="">-- Select customer --</option>'+a.map(x=>`<option value="${x.id}">${esc(x.customer_code||('CUS-'+String(x.id).padStart(4,'0')))} — ${esc(x.name)}</option>`).join('')}
   if(sel.dataset.lookup==='flock'){let a=await api('/flocks');sel.innerHTML='<option value="">-- Select flock batch --</option>'+a.map(x=>`<option value="${x.id}">${esc(x.batch)}${x.breed?' — '+esc(x.breed):''}</option>`).join('')}
 }
 if(p==='feed'){let q=document.querySelector('[name=received_kg]'),cost=document.querySelector('[name=total_cost]'),per=document.querySelector('[name=cost_per_kg]');let calc=()=>per.value=(Number(q.value)>0?(Number(cost.value||0)/Number(q.value)).toFixed(2):'0.00');q.oninput=cost.oninput=calc}
 if(p==='sales'){let q=document.querySelector('[name=quantity]'),price=document.querySelector('[name=price_per_tray]'),total=document.querySelector('[name=total]');let calc=()=>total.value=(Number(q.value||0)*Number(price.value||0)).toFixed(2);q.oninput=price.oninput=calc}
 let data=await api('/'+res);cache[res]=data;document.getElementById('table').innerHTML=makeTable(res,data);
 document.getElementById('form').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));for(let k in o)if(['received','cost_per_chick','mortality','culls','flock_id','trays','loose_eggs','received_kg','total_cost','cost_per_kg','consumed_kg','quantity','unit_cost','amount_paid','customer_id','price_per_tray','total','opening_debt','feed_credit','other_credit','paid'].includes(k))o[k]=o[k]===''?0:Number(o[k]);await api('/'+res,{method:'POST',body:JSON.stringify(o)});e.target.reset();renderPage(p)}
}
function makeTable(res,a){let cols={flocks:['batch','breed','received','mortality','culls','house'],production:['date','flock_batch','trays','loose_eggs','mortality'],feed:['date','type','supplier','received_kg','total_cost','cost_per_kg','consumed_kg'],purchases:['date','category','item','supplier','quantity','unit_cost','payment_status'],customers:['customer_code','name','phone','location'],sales:['date','customer','customer_code','quantity','price_per_tray','total','payment_status'],debts:['supplier_code','supplier','opening_debt','feed_credit','paid','remaining']}[res]||[];let labels={flock_batch:'flock batch no.',customer_code:'customer ID',supplier_code:'supplier ID',received_kg:'quantity kg',total_cost:'total cost',cost_per_kg:'cost per kg',price_per_tray:'price / tray'};return `<div class="tablewrap"><table><thead><tr>${cols.map(c=>`<th>${labels[c]||c.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${a.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function dashboard(){let d=await api('/dashboard'),m=d.metrics;metrics.innerHTML=[['🐔','Total Chicks (Current)',m.alive.toLocaleString(),`${Math.max(0,m.alive-m.mortality).toLocaleString()} alive | ${m.mortality} mortality`],['🌾','Feed Consumed (Total)',m.consumed.toFixed(0)+' kg','Feed Cost: '+money(m.feedCost)],['◉','Total Purchases',money(m.purchaseCost),'incl. credit/debt'],['💰','Total Sales',money(m.revenue),'from birds & eggs'],['↗','Net Profit',money(m.profit),'after recorded purchases']].map(x=>`<div class="metric"><div class="small">${x[0]} ${x[1]}</div><div class="num">${x[2]}</div><div class="sub">${x[3]}</div></div>`).join('');alerts.innerHTML=`<div class="alert red"><b>🔴 Supplier Debt Outstanding</b><strong>${money(m.debt)}</strong><span>Outstanding supplier balance</span></div><div class="alert orange"><b>🟠 Low Feed Stock</b><span>Review current feed stock and intake records.</span></div><div class="alert blue"><b>🔵 First Egg Recorded</b><strong>Aug 14, 2025</strong><span>Egg production has started.</span></div>`;recentPurchases.innerHTML=makeTable('purchases',d.purchases.slice(0,5));feedDaily.innerHTML=makeTable('feed',d.feed.slice(0,5));flockSummary.innerHTML=makeTable('production',d.prod.slice(0,5));eggSummary.innerHTML=`<div>First Egg Seen<br><b style="font-size:17px">Aug 14, 2025</b></div><hr><div>Recorded production<br><b style="font-size:17px">${m.eggs.toLocaleString()} eggs</b></div><hr><div>Tray rule: <b>1 tray = 30 eggs</b><br>Example: 2 trays + 4 eggs = 64 eggs</div>`;customerSummary.innerHTML=makeTable('customers',await api('/customers').then(x=>x.slice(0,5)));salesSummary.innerHTML=makeTable('sales',d.sales.slice(0,5));drawProd(d.prod);drawFeed(d.feed)}
function suppliersPage(){let f=document.getElementById('debtForm');f.onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(f));for(let k of ['opening_debt','feed_credit','other_credit','paid'])o[k]=Number(o[k]||0);await api('/debts',{method:'POST',body:JSON.stringify(o)});f.reset();renderPage('suppliers')};api('/debts').then(a=>table.innerHTML=makeTable('debts',a))}
function financePage(){api('/dashboard').then(d=>financeCards.innerHTML=[['Sales',money(d.metrics.revenue)],['Purchases',money(d.metrics.purchaseCost)],['Feed cost',money(d.metrics.feedCost)],['Profit',money(d.metrics.profit)]].map(x=>`<div class="metric"><div class="small">${x[0]}</div><div class="num">${x[1]}</div></div>`).join(''))}
async function settingsPage(){if(me.role!=='admin'){users.innerHTML='<p class="muted">User management is restricted to administrators.</p>';return}let a=await api('/users');users.innerHTML=makeTable('customers',a.map(u=>({name:u.username,phone:u.role,location:u.totp_enabled?'2FA enabled':'2FA not enabled'})))+'<hr><button class="primary" onclick="addUser()">Add authorized user</button>'}
async function setup2fa(){let r=await api('/auth/2fa/setup',{method:'POST'});modal.classList.remove('hidden');modalBody.innerHTML=`<h3>Enable two-factor authentication</h3><p>Scan this QR code with your authenticator app, then enter the 6-digit code.</p><img class="qr" src="${r.qr}" alt="TOTP QR"><div class="notice">If you cannot scan it, use secret: <b>${esc(r.secret)}</b></div><div class="field"><label>Authenticator code</label><input id="confirmOtp" inputmode="numeric"></div><button class="primary" onclick="confirm2fa()">Confirm 2FA</button> <button class="secondary" onclick="closeModal()">Cancel</button>`}
async function confirm2fa(){try{await api('/auth/2fa/confirm',{method:'POST',body:JSON.stringify({token:confirmOtp.value})});closeModal();alert('Two-factor authentication enabled.');}catch(e){alert(e.message)}}
async function addUser(){let u=prompt('New username');if(!u)return;let p=prompt('Temporary password');if(!p)return;let role=prompt('Role: admin or manager','manager');try{await api('/users',{method:'POST',body:JSON.stringify({username:u,password:p,role:role==='admin'?'admin':'manager'})});settingsPage()}catch(e){alert(e.message)}}
function closeModal(){modal.classList.add('hidden')}
function money(x){return new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(x||0)}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function drawProd(a){let c=document.getElementById('prodChart');if(!c)return;let x=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.scale(d,d);x.clearRect(0,0,w,h);let z=a.slice(0,14).reverse(),vals=z.map(p=>Number(p.trays||0)*30+Number(p.loose_eggs||0)),max=Math.max(1,...vals);x.strokeStyle='#159251';x.lineWidth=3;x.beginPath();z.forEach((p,i)=>{let xx=35+i*(w-55)/Math.max(1,z.length-1),yy=h-35-vals[i]/max*(h-65);i?x.lineTo(xx,yy):x.moveTo(xx,yy);x.fillStyle='#66756e';x.font='9px Arial';x.fillText((p.date||'').slice(5),xx-10,h-18)});x.stroke();z.forEach((p,i)=>{let xx=35+i*(w-55)/Math.max(1,z.length-1),yy=h-35-vals[i]/max*(h-65);x.beginPath();x.arc(xx,yy,4,0,Math.PI*2);x.fillStyle='#159251';x.fill()});x.fillStyle='#42534b';x.font='10px Arial';x.fillText('Eggs produced',12,14)}
function drawFeed(a){let c=document.getElementById('feedChart');if(!c)return;let x=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.scale(d,d);let s={'Chick Mash':0,Growers:0,Layers:0};a.forEach(f=>s[f.type]=(s[f.type]||0)+f.consumed_kg);let total=Object.values(s).reduce((a,b)=>a+b,0),cx=w*.4,cy=h/2,r=Math.min(w,h)*.3,colors=['#159251','#2e79dc','#6745d8'],ang=-Math.PI/2;Object.entries(s).forEach((q,i)=>{let b=ang+(q[1]/Math.max(1,total))*Math.PI*2;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,r,ang,b);x.closePath();x.fillStyle=colors[i];x.fill();ang=b});x.beginPath();x.arc(cx,cy,r*.55,0,Math.PI*2);x.fillStyle='#fff';x.fill();x.fillStyle='#233b31';x.textAlign='center';x.font='bold 13px Arial';x.fillText(total.toFixed(0)+' kg',cx,cy+5);x.textAlign='left';let y=35;Object.entries(s).forEach((q,i)=>{x.fillStyle=colors[i];x.fillRect(w*.7,y-8,9,9);x.fillStyle='#42534b';x.font='10px Arial';x.fillText(q[0],w*.74,y);x.fillText(total?Math.round(q[1]/total*100)+'%':'0%',w*.92,y);y+=27})}
function downloadReport(){window.location='/api/report.pdf'}
boot();
